language: java
sudo: required # to install flatbuffers
jdk:
  - openjdk8

addons:
  apt:
    update: true
    packages:
    - git
    - cmake
    - make

before_install:
  - chmod +x ./scripts/install-flatbuffers.sh
  - ./scripts/install-flatbuffers.sh

install: true

script:
  - ./gradlew prepareStaticAndAgent
 - ./gradlew test -x :agent-test:test
 - ./gradlew buildPlugin
